# [language-server.ruff]
# command = "ruff"
# args = ["server"]

[language-server.ruff.config.settings.lint]
select = ["E", "F", "S", "ASYNC", "BLE", "FLY",
"I", "C90", "PERF", "B", "FBT", "A", "PL",
"C4", "DTZ", "TID", "SIM", "SLOT", "ARG",
"PTH", "N", "UP", "FURB", "RUF", "TRY"]

ignore = ["E501"]

# [language-server.ty]
# command = "ty"
# args = ["server"]

[language-server.typos]
command = "typos-lsp"


[[language]]
name = "python"
language-servers = ["ruff", "ty", "typos"]
formatter = { command = "sh", args = [
  "-c",
  "ruff check --extend-select I --fix - | ruff format -"
] }

[[language]]
name = "rst"
language-servers = ["typos"]

[[language]]
name = "markdown"
language-servers = ["typos"]
